//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileReader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id_users { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string prenom { get; set; }
        public string nom { get; set; }
        public Nullable<int> admin { get; set; }
    }
}
